### ISSUE TITLE
Android module: features and ideas

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow-incubator#11]
Let's collect some ideas and features. 

@arrow-kt/maintainers Feel free to comment or edit this post to add/edit/fix anything you consider :+1: 

- [ ] Provide Android's main coroutine context
- [ ] Create explicit `evalOnMain` extension function based on future's `evalOn` (see arrow-kt/arrow#1394)
- [ ] Check how Proguard affects Arrow and provide any necessary proguard rules through gradle's `consumerProguardFiles` (see arrow-kt/arrow#1406)
- [ ] Update Arrow's Google samples repo with this module (see arrow-kt/arrow#454)
- [ ] Explore possibilities of an arrow-like ["declarative toolkit for building UI" such as Google's compose](https://developer.android.com/jetpack/compose/)
- [ ] Optional: LiveDataK wrapper for arrow-effects-android arrow-kt/arrow#1095
